// apps/react/src/components/Card/Card.tsx
import { useDisclosure, useClipboard, useToggle } from "@mantine/hooks";
import { Modal, Paper, Text, ActionIcon, Menu, Button } from "@mantine/core";
import {
  IconCopy,
  IconEdit,
  IconTrash,
  IconAdjustmentsHorizontal,
  IconQrcode,
} from "@tabler/icons-react";
import { FC, memo } from "react";
import { QRCodeSVG } from "qrcode.react";
import { notifications } from "@mantine/notifications";
import { DeleteLinkForm, EditLinkForm } from "components";
import { api } from "trpc";

export interface CardProps {
  id: string;
  url: string;
  slug: string;
  description?: string;
}

const MENU_ICON_SIZE = 18;

const Card: FC<CardProps> = ({ id, url, slug, description = "" }) => {
  const [isEditOpen, handleEditModal] = useDisclosure(false);
  const [isDeleteOpen, handleDeleteModal] = useDisclosure(false);
  const [isQRCodeOpen, handleQRCodeModal] = useDisclosure(false);
  const clipboard = useClipboard();
  const [menuOpened, toggleMenu] = useToggle([false, true] as const);
  const apiUtils = api.useUtils();

  const targetUrl = `${window.location.protocol}//${window.location.host}/s/${slug}`;

  const copyUrl = () => {
    clipboard.copy(targetUrl);
    notifications.show({
      title: "Success",
      message: "URL copied to clipboard",
      color: "green",
    });
  };

  const invalidateAllLinks = async () => apiUtils.link.allLinks.invalidate();

  const handleDeletionSuccess = async () => {
    handleDeleteModal.close();
    await invalidateAllLinks();
  };

  const handleEditSuccess = async () => {
    handleEditModal.close();
    await invalidateAllLinks();
  };

  return (
    <Paper
      p="md"
      shadow="xs"
      className="flex justify-between rounded-lg border border-gray-8 p-4 transition-all hover:shadow-lg"
    >
      <div className="flex flex-col w-2/3">
        <div className="flex items-center gap-x-3 mb-2 items-center w-full">
          <a
            className="text-lg font-semibold text-black dark:text-gray-1 transition-all hover:text-blue-6 dark:hover:text-blue-6 no-underline sm:max-w-[100px] truncate"
            target="_blank"
            rel="noreferrer"
            href={targetUrl}
          >
            /s/{slug}
          </a>
          <div className="flex items-center gap-x-1">
            <ActionIcon size="sm" variant="transparent" onClick={copyUrl}>
              <IconCopy />
            </ActionIcon>
            <ActionIcon
              size="sm"
              variant="transparent"
              onClick={handleQRCodeModal.open}
            >
              <IconQrcode />
            </ActionIcon>
          </div>
        </div>
        <Text className="text-gray-8 dark:text-gray-5 mb-1 truncate">
          {url}
        </Text>
        <Text className="text-gray-7 dark:text-gray-6 text-sm truncate">
          {description}
        </Text>
      </div>
      <div className="flex flex-col max-w-1/3">
        <Menu opened={menuOpened} onChange={toggleMenu}>
          <Menu.Target>
            <Button
              color="blue"
              size="xs"
              variant="outline"
              leftSection={<IconAdjustmentsHorizontal size={16} />}
              onClick={() => toggleMenu()}
            >
              Options
            </Button>
          </Menu.Target>

          <Menu.Dropdown>
            <Menu.Item
              leftSection={<IconCopy size={MENU_ICON_SIZE} />}
              onClick={copyUrl}
            >
              Copy
            </Menu.Item>
            <Menu.Item
              leftSection={<IconEdit size={MENU_ICON_SIZE} />}
              onClick={handleEditModal.open}
            >
              Edit
            </Menu.Item>
            <Menu.Item
              color="red"
              leftSection={<IconTrash size={MENU_ICON_SIZE} />}
              onClick={handleDeleteModal.open}
            >
              Delete
            </Menu.Item>
          </Menu.Dropdown>
        </Menu>
        <Modal
          centered
          opened={isEditOpen}
          onClose={handleEditModal.close}
          title={`Edit: /s/${slug}`}
        >
          <EditLinkForm
            handleSuccess={handleEditSuccess}
            linkId={id}
            url={url}
            description={description}
          />
        </Modal>
        <Modal
          centered
          opened={isDeleteOpen}
          onClose={handleDeleteModal.close}
          title={`Delete: /s/${slug}`}
        >
          <DeleteLinkForm handleSuccess={handleDeletionSuccess} linkId={id} />
        </Modal>

        <Modal
          opened={isQRCodeOpen}
          onClose={handleQRCodeModal.close}
          title={`QR Code for: ${slug}`}
          centered
        >
          <div className="flex flex-col items-center">
            <div className="w-10/12 xs:w-64 p-4 bg-white">
              <QRCodeSVG className="!w-full !h-full" value={targetUrl} />
            </div>
            <Text className="text-center mt-5 text-sm">
              Scan the QR code above to quickly access your URL on a mobile
              device.
            </Text>
          </div>
        </Modal>
      </div>
    </Paper>
  );
};

export default memo(Card);

// apps/vue/src/components/Card/Card.vue
<script setup lang="ts">
import { defineProps, withDefaults } from "vue";
import Button from "primevue/button";
import Dialog from "primevue/dialog";
import Menu from "primevue/menu";
import { useToast } from "primevue/usetoast";
import { useClipboard } from "@vueuse/core";
import { useToggle } from "@vueuse/core";
import QrcodeVue from "qrcode.vue";
import { EditLinkForm, DeleteLinkForm } from "@/components";
import { useQueryClient } from "@tanstack/vue-query";

interface CardProps {
  id: string;
  url: string;
  slug: string;
  description?: string;
}

const { id, url, slug, description } = withDefaults(defineProps<CardProps>(), {
  description: "",
});

const { copy, isSupported } = useClipboard();
const toast = useToast();

const targetUrl = `${window.location.protocol}//${window.location.host}/s/${slug}`;

const copyUrl = () => {
  if (isSupported) {
    copy(targetUrl);
    toast.add({
      severity: "success",
      summary: "Success",
      detail: "URL copied to clipboard",
      life: 3000,
    });
  } else {
    toast.add({
      severity: "error",
      summary: "Error",
      detail: "Clipboard not supported",
      life: 3000,
    });
  }
};

const [isEditOpen, toggleEditModal] = useToggle(false);
const [isDeleteOpen, toggleDeleteModal] = useToggle(false);
const [isQRCodeOpen, toggleQRCodeModal] = useToggle(false);
const [menuOpened, toggleMenu] = useToggle(false);

const queryClient = useQueryClient();
const invalidateAllLinks = async () => {
  await queryClient.invalidateQueries({
    queryKey: ["allLinks"],
  });
};
const handleDeletionSuccess = async () => {
  toggleDeleteModal(false);
  await invalidateAllLinks();
};

const handleEditSuccess = async () => {
  toggleEditModal(false);
  await invalidateAllLinks();
};

const menuItems = [
  { label: "Copy", icon: "pi pi-copy", command: copyUrl },
  { label: "Edit", icon: "pi pi-pencil", command: () => toggleEditModal() },
  { label: "Delete", icon: "pi pi-trash", command: () => toggleDeleteModal() },
];
</script>

<template>
  <div
    class="flex justify-between rounded-lg p-4 transition-all hover:shadow-lg bg-surface-300 text-white"
  >
    <div class="flex flex-col w-2/3">
      <div class="flex items-center gap-x-3 mb-2 items-center w-full">
        <a
          class="text-lg font-semibold text-white dark:text-gray-1 transition-all hover:text-blue-6 dark:hover:text-blue-6 no-underline sm:max-w-[100px] truncate"
          target="_blank"
          rel="noreferrer"
          :href="targetUrl"
        >
          /s/{{ slug }}
        </a>
        <div class="flex items-center gap-x-1">
          <Button size="small" icon="pi pi-copy" @click="copyUrl" />
          <Button
            size="small"
            icon="pi pi-qrcode"
            @click="() => toggleQRCodeModal()"
          />
        </div>
      </div>
      <p class="text-white dark:text-gray-5 mb-1 truncate">
        {{ url }}
      </p>
      <p class="text-gray-7 dark:text-gray-6 text-sm truncate">
        {{ description }}
      </p>
    </div>
    <div class="flex flex-col max-w-1/3">
      <Button
        label="Options"
        icon="pi pi-ellipsis-v"
        @click="() => toggleMenu()"
        outlined
        size="small"
      />
      <Menu :model="menuItems" :popup="true" v-model="menuOpened" ref="menu" />
      <Dialog header="Edit" :visible="isEditOpen" :modal="true">
        <EditLinkForm
          @success="handleEditSuccess"
          :linkId="id"
          :url="url"
          :description="description"
        />
      </Dialog>
      <Dialog header="Delete" :visible="isDeleteOpen" :modal="true">
        <DeleteLinkForm @success="handleDeletionSuccess" :linkId="id" />
      </Dialog>
      <Dialog header="QR Code" :visible="isQRCodeOpen" :modal="true">
        <qrcode-vue render-as="svg" :value="targetUrl" />
        <p class="text-center mt-5 text-sm">
          Scan the QR code above to quickly access your URL on a mobile device.
        </p>
      </Dialog>
    </div>
  </div>
</template>
