// apps/react/src/layouts/DashboardLayout.tsx
import React, { FC } from "react";
import { Link } from "react-router-dom";
import { IconPlus } from "@tabler/icons-react";
import { CommonLayout } from "./CommonLayout";
import { Title, Button } from "@mantine/core";

interface DashboardLayoutProps {
  children: React.ReactNode;
}

const DashboardLayout: FC<DashboardLayoutProps> = ({ children }) => {
  return (
    <CommonLayout>
      <div className="border-b-2 border-gray-8 mt-1">
        <div className="w-full flex items-center justify-between">
          <Title className="text-2xl" order={2}>
            Dashboard
          </Title>
          <Link to="/new">
            <Button size="sm" leftSection={<IconPlus size={18} />}>
              Create new link
            </Button>
          </Link>
        </div>
      </div>
      {children}
    </CommonLayout>
  );
};

export default DashboardLayout;

// apps/vue/src/layouts/DashboardLayout.vue
<script setup lang="ts">
import Button from "primevue/button";
import CommonLayout from "./CommonLayout.vue";
</script>

<template>
  <CommonLayout :require-auth="true">
    <div class="border-b-2 border-gray-8 mt-1">
      <div class="w-full flex items-center justify-between">
        <h2 class="text-2xl">Dashboard</h2>
        <router-link to="/new">
          <Button size="small" icon="pi pi-plus" label="Create new link" />
        </router-link>
      </div>
    </div>
    <slot></slot>
  </CommonLayout>
</template>
