// apps/vue/src/components/Header/Header.vue
<script setup lang="ts">
import AuthUserMenu from "./AuthUserMenu.vue";
</script>

<template>
  <header class="w-full my-3">
    <div
      class="container max-w-4xl mx-auto flex items-center justify-between relative"
    >
      <router-link
        to="/"
        class="text-3xl md:text-4xl font-bold no-underline text-primary-500"
      >
        yurl
      </router-link>

      <div class="flex gap-x-3">
        <AuthUserMenu />
      </div>
    </div>
  </header>
</template>

// apps/react/src/components/Header/Header.tsx
import { FC } from "react";
import { Link } from "react-router-dom";
import { Container } from "@mantine/core";
import CommandButton from "./CommandButton";
import AuthUserMenu from "./AuthUserMenu";
import ThemeButton from "./ThemeButton";

const Header: FC = () => {
  return (
    <header className="w-full py-6">
      <Container className="flex items-center justify-between items-center">
        <Link
          className="inline-block text-4xl font-extrabold text-blue-6 no-underline"
          to="/"
        >
          yurl
        </Link>

        <div className="flex gap-x-3">
          <ThemeButton />
          <CommandButton />
          <AuthUserMenu />
        </div>
      </Container>
    </header>
  );
};

export default Header;
